Wedding::Application.config.action_mailer.delivery_method = :smtp
Wedding::Application.config.action_mailer.raise_delivery_errors = :true
Wedding::Application.config.action_mailer.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => 'tworingstorulethemall.com',
  :user_name            => 'wedding@tworingstorulethemall.com',
  :password             => '1Houdini!',
  :authentication       => :plain,
  :enable_starttls_auto => true  }